# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr)
arr.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
arr = np.arange(10).reshape(2,5)
arr_ones = np.ones((2,5), dtype = np.int)
np.vstack((arr,arr_ones))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
arr = np.arange(10).reshape(2,5)
arr_ones = np.ones((2,5), dtype = np.int)
np.hstack((arr,arr_ones))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
arr.ravel() # retuns a 1d view of the array
arr.flatten() # returns a copy of the original array
arr.reshape(arr.size) # retuns a 1d view of the array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [6]:
arr3d = np.arange(15).reshape(3,1,5)
arr3d.ravel() # retuns a 1d view of the array
arr3d.flatten() # returns a copy of the original array
arr3d.reshape(arr3d.size) # retuns a 1d view of the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [7]:
arr = np.arange(15)
arr.resize(5,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [8]:
arr2d = arr = np.rint(np.abs(np.random.randn(5,5)*10))
print(arr2d)
np.square(arr2d)

[[ 2.  6.  4.  1.  9.]
 [ 0.  8. 18. 16.  2.]
 [15.  3.  7.  6. 17.]
 [10.  5.  4.  1.  6.]
 [ 9.  6.  8. 17.  8.]]


array([[  4.,  36.,  16.,   1.,  81.],
       [  0.,  64., 324., 256.,   4.],
       [225.,   9.,  49.,  36., 289.],
       [100.,  25.,  16.,   1.,  36.],
       [ 81.,  36.,  64., 289.,  64.]])

## Question:8

### Create 5x6 an array and find the mean?

In [9]:
arr = np.rint(np.abs(np.random.randn(5,5)*10))
print(arr)
arr.mean()

[[ 0.  1.  7. 14. 13.]
 [14.  5.  6. 10. 11.]
 [ 1. 15. 14.  0.  0.]
 [ 3.  3. 22. 16.  6.]
 [13. 10.  9.  5.  1.]]


7.96

## Question:9

### Find the standard deviation of the previous array in Q8?

In [10]:
print(arr)
arr.std()

[[ 0.  1.  7. 14. 13.]
 [14.  5.  6. 10. 11.]
 [ 1. 15. 14.  0.  0.]
 [ 3.  3. 22. 16.  6.]
 [13. 10.  9.  5.  1.]]


6.0031991471214745

## Question:10

### Find the median of the previous array in Q8?

In [11]:
print(arr)
np.median(arr)

[[ 0.  1.  7. 14. 13.]
 [14.  5.  6. 10. 11.]
 [ 1. 15. 14.  0.  0.]
 [ 3.  3. 22. 16.  6.]
 [13. 10.  9.  5.  1.]]


7.0

## Question:11

### Find the transpose of the previous array in Q8?

In [12]:
print(arr)
# np.transpose(arr)
arr.T

[[ 0.  1.  7. 14. 13.]
 [14.  5.  6. 10. 11.]
 [ 1. 15. 14.  0.  0.]
 [ 3.  3. 22. 16.  6.]
 [13. 10.  9.  5.  1.]]


array([[ 0., 14.,  1.,  3., 13.],
       [ 1.,  5., 15.,  3., 10.],
       [ 7.,  6., 14., 22.,  9.],
       [14., 10.,  0., 16.,  5.],
       [13., 11.,  0.,  6.,  1.]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [13]:
arr2d = arr = np.rint(np.abs(np.random.randn(4,4)*10))
print(arr2d)
print(arr2d.trace())
print(arr2d.diagonal().sum())

[[12. 16. 10.  9.]
 [ 8.  8.  5.  0.]
 [ 1.  8.  9.  1.]
 [ 4.  7.  9.  5.]]
34.0
34.0


## Question:13

### Find the determinant of the previous array in Q12?

In [14]:
np.linalg.det(arr2d)

-1958.9999999999989

## Question:14

### Find the 5th and 95th percentile of an array?

In [15]:
print(np.percentile(arr2d, 5))
print(np.percentile(arr2d, 95))

0.75
13.0


## Question:15

### How to find if a given array has any null values?

In [16]:
np.isnan(arr2d).sum() # checks how many null values are there in an array

0