# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
array_1 = np.arange(10,49)

4. Find the shape of previous array in question 3

In [4]:
print(array_1.shape)
# or
np.shape(array_1)

(39,)


(39,)

5. Print the type of the previous array in question 3

In [5]:
print(array_1)
array_1

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

6. Print the numpy version and the configuration


In [6]:
print(np.version.version)
np.show_config()

1.18.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


7. Print the dimension of the array in question 3


In [7]:
array_1.ndim

1

8. Create a boolean array with all the True values

In [8]:
np.full(5, True)

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [9]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

10. Create a three dimensional array



In [10]:
np.arange(32).reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
arr = np.arange(10)
print(arr)
arr[::-1]

[0 1 2 3 4 5 6 7 8 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
v_array = np.zeros(10)
v_array.put(4,1)
print(v_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
np.eye(3)
# or
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.asarray(arr,dtype=np.float64)
print(arr2.dtype)
arr2

float64


array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1 * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
comp_array = arr1 > arr2
comp_array

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
print(arr)
arr[arr%2==1]

[1 2 3 4 5]


array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr[arr%2==1] = -1
arr

array([-1,  2, -1,  4, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
print(arr)
arr[[5,6,7,8]] = 12
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
array_border = np.ones((4,4), dtype=np.int)
array_border[1:-1,1:-1] = 0
array_border

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1,1] =12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d = np.arange(10).reshape(2,5)
print(arr2d)
arr2d[0:1,:]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d = np.arange(10).reshape(2,5)
print(arr2d)
arr2d[1:,1:2]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[6]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr2d = np.arange(10).reshape(2,5)
print(arr2d)
arr2d[:,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
rarray = np.random.randn(10,10)
print(f'The minimum value from the random array is {rarray.min()}')
print(f'The maximum value from the random array is {rarray.max()}')

The minimum value from the random array is -3.4251531895690133
The maximum value from the random array is 2.815026975327285


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[names!='Will']

array([[ 0.85225705, -0.68913076,  0.54778244,  0.72577118],
       [-1.04943711, -2.10158693,  0.84435417,  0.33525815],
       [ 0.33669843, -1.43529896, -1.16815842, -1.24689634],
       [-1.08503862, -0.32924713,  0.25374913,  0.51612593],
       [-0.70662619, -0.11703481,  0.46615395, -0.80042017]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
data[(names!='Will') & (names!='Joe')]

array([[ 0.05728679,  0.08633445, -0.68096204,  0.88463074],
       [ 0.95639516,  1.48265722,  1.46775879, -0.15780441]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
np.linspace(1,15, num=5*3, dtype=np.float).reshape(5,3)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
arr2d = np.linspace(1,16, num=2*2*4, dtype=np.float).reshape(2, 2, 4)
print(arr2d)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [33]:
arr2d.T

array([[[ 1.,  9.],
        [ 5., 13.]],

       [[ 2., 10.],
        [ 6., 14.]],

       [[ 3., 11.],
        [ 7., 15.]],

       [[ 4., 12.],
        [ 8., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.sqrt(np.arange(10))
arr[arr < 0.5] = 0
arr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [54]:
arr1 = np.abs(np.random.randn(12)*10).astype(np.int)
arr2 = np.abs(np.random.randn(12)*10).astype(np.int)
arr3 = np.miimum(arr1,arr2)
print([f"First Array:{arr1}"])
print([f"Second Array:{arr2}"])
print([f"Array with largest values:{arr3}"])

['First Array:[ 7  2 18 15  1  4  3  7 10  5  3  1]']
['Second Array:[12  7 13  3 13 15  3  1  9 17  3  5]']
['Array with largest values:[ 7  2 13  3  1  4  3  1  9  5  3  1]']


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.sort(np.unique(names))

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [ ]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [ ]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)
newColumn = np.array([[10,10,10]])
sampleArray[:,1:2] = newColumn.reshape(sampleArray[:,1:2].shape)
print(sampleArray)

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x@y
# or
# x.dot(y)
# np.dot(x,y)

40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
rd = np.random.randn(20)
print(rd)
rd.cumsum()